name: RandomItemXP
version: 1.0
main: org.electroraven.randomItemXP.RandomItemXP
commands:
  getRandomizer:
    description: Gives a randomizer item.
    usage: /getRandomizer
  startlevelrandomizer:
    description: Activates the level randomizer system.
    usage: /startlevelrandomizer
  stoplevelrandomizer:
    description: Deactivates the level randomizer system.
    usage: /stoplevelrandomizer
